name: adalayers
kwargs:
  base_model: "facebook/bart-large-cnn"
  project_dim: 64
  layers_num: 13
  layer_in_dim: 1024
  attention_heads_num: 16
  num_classes: ${dataset.num_classes}
  attention_dropout_prob: 0.3
  freeze_distribution: False
  lambda_distribution_entropy: 0.0
  alpha_distribution: 64
  generate_fake_decoder_input_ids: True
