name: adalayers
kwargs:
  base_model: "FacebookAI/roberta-large"
  project_dim: 64
  layers_num: 24
  layer_in_dim: 1024
  attention_heads_num: 16
  num_classes: ${dataset.num_classes}
  attention_dropout_prob: 0.3
  freeze_distribution: False
  lambda_distribution_entropy: 0.001
  alpha_distribution: 64
