defaults:
  - model: adalayers_roberta_large
  - optimization: adam
  - tokenizer_pretrained: adalayers_roberta_large
  - dataset: cola
  - hydra: common
  - _self_

optimization:
  max_epochs: 256
  batch_size: 300
  batch_size_eval: 300
  precision: "16-mixed"
  early_stop_patience: 30
  lr_patience: 25

model:
  kwargs:
    lambda_distribution_entropy: 0.0
    alpha_distribution: 64
    add_pos_embeddings: True

wandb:
  name: ${cat:"diploma", ${dataset.name}, ${model.name}}
