defaults:
  - model: adalayers_tok_roberta_large
  - optimization: adam
  - tokenizer_pretrained: adalayers_roberta_large_conll
  - dataset: conll
  - hydra: common
  - _self_

optimization:
  max_epochs: 256
  batch_size: 256
  batch_size_eval: 512
  mode: token_classification
  early_stop_patience: 20
  optim_kwargs:
    lr: 8e-5
    weight_decay: 0.001

wandb:
  name: ${cat:"final", ${dataset.name}, ${model.name}}
