defaults:
  - model: adalayers_roberta_base
  - optimization: adam
  - tokenizer_pretrained: roberta_base
  - dataset: imdb
  - hydra: common
  - _self_

wandb:
  name: ${cat:"test", ${dataset.name}, ${model.name}}
