defaults:
  - model: adalayers_bert
  - optimization: adam
  - tokenizer_pretrained: bert_mlm
  - dataset: imdb
  - hydra: common
  - _self_

optimization:
  max_epochs: 1

wandb:
  name: ${cat:"final", ${dataset.name}, ${model.name}}
