defaults:
  - adalayers_conll
  - override model: adalayers_bart
  - override tokenizer_pretrained: adalayers_bart
  - _self_

optimization:
  max_epochs: 256
  batch_size_eval: 900

tokenizer_pretrained:
  add_prefix_space: True

model:
  name: adalayers_token

logging:
  name: ${cat:"diploma_bart", ${dataset.name}, ${model.name}}
