defaults:
  - model: adalayers_roberta_large
  - optimization: adam
  - tokenizer_pretrained: adalayers_roberta_large
  - dataset: rte
  - hydra: common
  - _self_

optimization:
  max_epochs: 128
  batch_size: 128
  batch_size_eval: 128
  lr_patience: 10
  best_metric: acc

model:
  kwargs:
    lambda_distribution_entropy: 0.05
    alpha_distribution: 256
    attention_heads_num: 8

wandb:
  name: ${cat:"final", ${dataset.name}, ${model.name}}
