defaults:
  - model: adalayers_bert_mlm
  - optimization: adam
  - tokenizer_pretrained: bert_base_uncased
  - dataset: cola
  - hydra: common
  - _self_

optimization:
  max_epochs: 16

wandb:
  name: ${cat:"test", ${dataset.name}, ${model.name}}
