defaults:
  - model: adalayers_roberta_large
  - optimization: adam
  - tokenizer_pretrained: adalayers_roberta_large
  - dataset: imdb
  - hydra: common
  - _self_

optimization:
  max_epochs: 128
  batch_size: 400
  batch_size_eval: 400
  precision: "16-mixed"
  optim_kwargs:
    lr: 1e-4
    weight_decay: 0.001

model:
  kwargs:
    lambda_distribution_entropy: 0.0
    alpha_distribution: 96

wandb:
  name: ${cat:"diploma", ${dataset.name}, ${model.name}}
